[build]
builder = "nixpacks"

[build.nixpacksConfig]
providers = ["node"]

[build.nixpacksConfig.phases.setup]
nixPkgs = ["nodejs_20", "pnpm"]

[build.nixpacksConfig.phases.install]
cmds = ["pnpm install --frozen-lockfile"]

[build.nixpacksConfig.phases.build]
cmds = ["pnpm run build"]

[build.nixpacksConfig.start]
cmd = "pnpm run preview --host 0.0.0.0 --port $PORT"

[deploy]
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[environments.production]
variables = {}
