[build]
builder = "nixpacks"

[deploy]
startCommand = "pnpm run build && npx serve -s dist -l $PORT"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
